<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2.2 setup script
 * Date: Mon, 27 Aug 2012 12:25:44 +0800
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = TRUE;
?>
